In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [57]:
data=pd.read_csv("../given/practical6/METABRIC_RNA_Mutation.csv")
data.head()

/tmp/ipykernel_5012/689434496.py:1: DtypeWarning: Columns (678,688,690,692) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv("../given/practical6/METABRIC_RNA_Mutation.csv")


patient_id  age_at_diagnosis type_of_breast_surgery    cancer_type  \
0           0             75.65             MASTECTOMY  Breast Cancer   
1           2             43.19      BREAST CONSERVING  Breast Cancer   
2           5             48.87             MASTECTOMY  Breast Cancer   
3           6             47.68             MASTECTOMY  Breast Cancer   
4           8             76.97             MASTECTOMY  Breast Cancer   

                        cancer_type_detailed cellularity  chemotherapy  \
0           Breast Invasive Ductal Carcinoma         NaN             0   
1           Breast Invasive Ductal Carcinoma        High             0   
2           Breast Invasive Ductal Carcinoma        High             1   
3  Breast Mixed Ductal and Lobular Carcinoma    Moderate             1   
4  Breast Mixed Ductal and Lobular Carcinoma        High             1   

  pam50_+_claudin-low_subtype  cohort er_status_measured_by_ihc  ... mtap_mut  \
0                 claudin-low     1.0                   Positve  ...        0   
1                        LumA     1.0                   Positve  ...        0   
2                        LumB     1.0                   Positve  ...        0   
3                        LumB     1.0                   Positve  ...        0   
4                        LumB     1.0                   Positve  ...        0   

   ppp2cb_mut smarcd1_mut nras_mut ndfip1_mut  hras_mut prps2_mut smarcb1_mut  \
0           0           0        0          0         0         0           0   
1           0           0        0          0         0         0           0   
2           0           0        0          0         0         0           0   
3           0           0        0          0         0         0           0   
4           0           0        0          0         0         0           0   

  stmn2_mut  siah1_mut  
0         0          0  
1         0          0  
2         0          0  
3         0          0  
4         0          0  

[5 rows x 693 columns]

In [58]:
data=data.dropna()
x =data.drop("death_from_cancer", axis=1)
y =data["death_from_cancer"]

In [59]:
x = pd.get_dummies(x)

In [60]:

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline


In [61]:
x_tr, x_test, y_tr, y_test = train_test_split(x, y, test_size=0.2, random_state=200)

In [ ]:
# LogisticRegression

In [62]:
model = LogisticRegression().fit(x_tr, y_tr)
predTrain = model.predict(x_tr)
predTest = model.predict(x_test)

print(confusion_matrix(y_tr, predTrain))
print(classification_report(y_tr, predTrain))
print()
print(confusion_matrix(y_test, predTest))
print(classification_report(y_test, predTest))

[[208  35  56]
 [ 53  83  53]
 [ 36  36 313]]
                      precision    recall  f1-score   support

     Died of Disease       0.70      0.70      0.70       299
Died of Other Causes       0.54      0.44      0.48       189
              Living       0.74      0.81      0.78       385

            accuracy                           0.69       873
           macro avg       0.66      0.65      0.65       873
        weighted avg       0.68      0.69      0.69       873


[[44 11 16]
 [18 21 10]
 [10  9 80]]
                      precision    recall  f1-score   support

     Died of Disease       0.61      0.62      0.62        71
Died of Other Causes       0.51      0.43      0.47        49
              Living       0.75      0.81      0.78        99

            accuracy                           0.66       219
           macro avg       0.63      0.62      0.62       219
        weighted avg       0.65      0.66      0.66       219



/home/aadityapal/.conda/envs/notebook/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [63]:
model = DecisionTreeClassifier().fit(x_tr, y_tr)
predTrain = model.predict(x_tr)
predTest= model.predict(x_test)
print("Train")
print(confusion_matrix(y_tr, predTrain))
print()
print(classification_report(y_tr, predTrain))
print()
print()
print("Test")
print(confusion_matrix(y_test, predTest))
print()
print(classification_report(y_test, predTest))


Train
[[299   0   0]
 [  0 189   0]
 [  0   0 385]]

                      precision    recall  f1-score   support

     Died of Disease       1.00      1.00      1.00       299
Died of Other Causes       1.00      1.00      1.00       189
              Living       1.00      1.00      1.00       385

            accuracy                           1.00       873
           macro avg       1.00      1.00      1.00       873
        weighted avg       1.00      1.00      1.00       873



Test
[[46 25  0]
 [23 26  0]
 [ 0  0 99]]

                      precision    recall  f1-score   support

     Died of Disease       0.67      0.65      0.66        71
Died of Other Causes       0.51      0.53      0.52        49
              Living       1.00      1.00      1.00        99

            accuracy                           0.78       219
           macro avg       0.73      0.73      0.73       219
        weighted avg       0.78      0.78      0.78       219



In [64]:
# Random Forest

In [65]:
model = RandomForestClassifier().fit(x_tr, y_tr)
predTain = model.predict(x_tr)
predTest= model.predict(x_test)
print("Train")
print(confusion_matrix(y_tr, predTrain))
print(classification_report(y_tr, predTrain))
print()
print("Test")
print(confusion_matrix(y_test, predTest))
print(classification_report(y_test,predTest))

Train
[[299   0   0]
 [  0 189   0]
 [  0   0 385]]
                      precision    recall  f1-score   support

     Died of Disease       1.00      1.00      1.00       299
Died of Other Causes       1.00      1.00      1.00       189
              Living       1.00      1.00      1.00       385

            accuracy                           1.00       873
           macro avg       1.00      1.00      1.00       873
        weighted avg       1.00      1.00      1.00       873


Test
[[46  6 19]
 [30  7 12]
 [ 1  1 97]]
                      precision    recall  f1-score   support

     Died of Disease       0.60      0.65      0.62        71
Died of Other Causes       0.50      0.14      0.22        49
              Living       0.76      0.98      0.85        99

            accuracy                           0.68       219
           macro avg       0.62      0.59      0.57       219
        weighted avg       0.65      0.68      0.64       219



In [66]:
# find k for Select K Best 
param={"kbest__k":[10,20,30, 40, 50, 100, 200, 400, 1000,2000, 4000, 5000]}
model = GridSearchCV(Pipeline([("kbest", SelectKBest(f_classif)), ("classify", RandomForestClassifier())]),param_grid=param, cv=10)
model.fit(x,y)
model.best_params_

/home/aadityapal/.conda/envs/notebook/lib/python3.12/site-packages/sklearn/feature_selection/_univariate_selection.py:112: UserWarning: Features [  10  505  571  575  592  598  610  625  639  657  695  728  739  740
  754  760  778  811  814  862  873  877  908  936  937  943  951  982
 1004 1020 1024 1028 1037 1076 1105 1128 1134 1142 1169 1234 1257 1265
 1277 1287 1314 1319 1323 1326 1337 1340 1350 1351 1353 1379 1402 1408
 1418 1427 1468 1469 1489 1492 1514 1523 1528 1542 1545 1561 1575 1590
 1594 1598 1625 1642 1650 1652 1668 1670 1674 1687 1724 1758 1799 1867
 1871 1883 1893 1913 1923 1927 1929 1933 1945 1956 2019 2024 2052 2056
 2080 2082 2095 2144 2162 2183 2184 2209 2219 2226 2237 2242 2289 2311
 2324 2332 2389 2460 2516 2525 2564 2587 2604 2640 2651 2696 2706 2707
 2723 2726 2784 2790 2810 2813 2837 2840 2845 2851 2898 2899 2950 2955
 2957 2970 2980 2996 3009 3063 3068 3095 3120 3123 3128 3129 3132 3133
 3140 3143 3153 3160 3192 3197 3201 3204 3208 3248 3250 3252 3263 3276
 32

{'kbest__k': 40}

In [67]:
suggest = SelectKBest(f_classif, k=20).fit(x,y)
cols = suggest.get_support(indices=True)
x.iloc[:, cols]

/home/aadityapal/.conda/envs/notebook/lib/python3.12/site-packages/sklearn/feature_selection/_univariate_selection.py:112: UserWarning: Features [  10  505 5285 5292] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
/home/aadityapal/.conda/envs/notebook/lib/python3.12/site-packages/sklearn/feature_selection/_univariate_selection.py:113: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw
/home/aadityapal/.conda/envs/notebook/lib/python3.12/site-packages/sklearn/feature_selection/_univariate_selection.py:113: RuntimeWarning: invalid value encountered in divide
  f = msb / msw


patient_id  age_at_diagnosis  chemotherapy  cohort  \
1              2             43.19             0     1.0   
4              8             76.97             1     1.0   
5             10             78.77             0     1.0   
8             28             86.41             0     1.0   
9             35             84.22             0     1.0   
...          ...               ...           ...     ...   
1618        6232             71.22             0     5.0   
1619        6233             70.65             0     5.0   
1621        6237             75.62             0     5.0   
1623        6239             52.84             1     5.0   
1664        6346             63.20             0     5.0   

      lymph_nodes_examined_positive  nottingham_prognostic_index  \
1                               0.0                        4.020   
4                               8.0                        6.080   
5                               0.0                        4.062   
8                               1.0                        5.032   
9                               0.0                        3.056   
...                             ...                          ...   
1618                            4.0                        5.060   
1619                            0.0                        2.040   
1621                            0.0                        4.040   
1623                            6.0                        5.040   
1664                            0.0                        3.044   

      overall_survival_months  overall_survival  tumor_size  tumor_stage  \
1                   84.633333                 1        10.0          1.0   
4                   41.366667                 0        40.0          2.0   
5                    7.800000                 0        31.0          4.0   
8                   36.566667                 0        16.0          2.0   
9                   36.266667                 0        28.0          2.0   
...                       ...               ...         ...          ...   
1618                85.000000                 0        30.0          2.0   
1619               201.166667                 1        20.0          1.0   
1621               105.200000                 0        20.0          1.0   
1623               200.333333                 1        20.0          2.0   
1664               281.500000                 1        22.0          2.0   

         myc    jak1   aurka   casp8   lama2  cdkn2c  hsd17b11  \
1     0.7248  0.9804 -0.3052  1.8819  0.3336  0.5189   -0.7837   
4     0.5223  0.0461  0.5882  1.8931 -0.7579  2.6149    0.0493   
5    -0.8320  0.7215  0.9681  0.1365  0.0893 -0.1684    0.8457   
8     1.9134 -0.0414  0.4572 -1.3110 -1.2117 -0.2183   -0.9126   
9    -2.8359 -0.7607 -0.2941  1.1160 -1.1881 -1.7546   -1.0184   
...      ...     ...     ...     ...     ...     ...       ...   
1618 -0.7303  0.6702 -0.9972  1.5518  1.2290 -0.2712    0.3369   
1619 -0.5896  1.2632 -0.3726  0.1572  0.8305 -0.0471    0.3443   
1621  1.2596  0.7989  1.6543 -0.0027 -1.3781  0.8505   -0.1045   
1623  0.0407  1.1565 -0.3215 -0.4587  0.7945 -0.2831    0.4986   
1664 -1.9342 -1.3989  0.2190 -1.0588 -0.5700 -0.5147   -1.1709   

      inferred_menopausal_state_Post  inferred_menopausal_state_Pre  \
1                              False                           True   
4                               True                          False   
5                               True                          False   
8                               True                          False   
9                               True                          False   
...                              ...                            ...   
1618                            True                          False   
1619                            True                          False   
1621                            True                          False   
1623                            True                

In [68]:
xNew = SelectKBest(f_classif,k=20).fit_transform(x, y)

/home/aadityapal/.conda/envs/notebook/lib/python3.12/site-packages/sklearn/feature_selection/_univariate_selection.py:112: UserWarning: Features [  10  505 5285 5292] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
/home/aadityapal/.conda/envs/notebook/lib/python3.12/site-packages/sklearn/feature_selection/_univariate_selection.py:113: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw
/home/aadityapal/.conda/envs/notebook/lib/python3.12/site-packages/sklearn/feature_selection/_univariate_selection.py:113: RuntimeWarning: invalid value encountered in divide
  f = msb / msw


In [69]:
x_tr, x_test, y_tr, y_test = train_test_split(xNew, y, test_size=0.2)

In [70]:
model = RandomForestClassifier().fit(x_tr, y_tr)
predTrain =model.predict(x_tr)
predTest=model.predict(x_test)

print(confusion_matrix(y_tr, predTrain))
print(classification_report(y_tr, predTrain))
print()
print(confusion_matrix(y_test, predTest))
print(classification_report(y_test, predTest))

[[289   0   0]
 [  0 189   0]
 [  0   0 395]]
                      precision    recall  f1-score   support

     Died of Disease       1.00      1.00      1.00       289
Died of Other Causes       1.00      1.00      1.00       189
              Living       1.00      1.00      1.00       395

            accuracy                           1.00       873
           macro avg       1.00      1.00      1.00       873
        weighted avg       1.00      1.00      1.00       873


[[64 17  0]
 [17 32  0]
 [ 0  0 89]]
                      precision    recall  f1-score   support

     Died of Disease       0.79      0.79      0.79        81
Died of Other Causes       0.65      0.65      0.65        49
              Living       1.00      1.00      1.00        89

            accuracy                           0.84       219
           macro avg       0.81      0.81      0.81       219
        weighted avg       0.84      0.84      0.84       219

