In [51]:
import numpy as np
import random

In [60]:
inputVec = []
for i in range(4):
    temp=[]
    for j in range(4):
        temp.append(-1 if random.randint(0,1)<1 else 1)
    inputVec.append(temp)

exemplars =[[-1,-1,-1,-1], [1,1,1,1]]
weights = []

inputVec = np.array(inputVec)
for i in range(len(exemplars)):
    weights.append(inputVec[i]//2)
bias = len(inputVec)//2

print(inputVec)

activations = np.dot(np.array(inputVec), np.array(weights).T)+bias
activations


[[ 1 -1 -1  1]
 [ 1  1  1  1]
 [ 1 -1 -1 -1]
 [-1  1 -1  1]]


array([[4, 2],
       [0, 2],
       [4, 2],
       [2, 2]])

In [62]:
#max net for determining which class it belongs to
epsilon =0.6
for i in range(activations.shape[0]):
    while(min(activations[i])>0):
        for j in range(activations.shape[1]):
            val = epsilon*sum(activations[i][k] for k in range(activations.shape[1]) if k!=j)
            act = activations[i][j] - val
            if(act<0):
                act =0
            activations[i][j] = act
print(activations)

[[2 0]
 [0 2]
 [2 0]
 [0 2]]
